(defvar *aobjects* (list))
(defvar *bobjects* (list *1* *2* *3* *4*))
(defvar *cobjects* (list *5* *6*))
(defvar *dobjects* (list *7* *8*))
(defvar *fobjects* (list))
(defvar *gobjects* (list))
(defvar *iobjects* (list))
(defvar *kobjects* (list))
(defvar *lobjects* (list))
(defvar *mobjects* (list))
(defvar *nobjects* (list))
(defvar *oobjects* (list))
(defvar *pobjects* (list))
(defvar *qobjects* (list))
